### ISSUE TITLE
Round 0 and Round 1

### ISSUE THREAD

**Issue by arsangeta** [dratul/eb04_Probably_FFT_as_sample_interpolator#2]
Round 0

About the lab: Write only about lab.  The details like you mention 3rd year b.tech and univ that is written later
Menotr Institute: KIET Group of Institutions, Delhi-NCR, Ghaziabad
Remove the faculty details from contributors list

Round 1

Focus Area: Justify why it is Reinforce theoretical concept and Data Analysis
Learning objective: Can we add some APPLY learning objective
Instructional Strategy: Not matching with learning objective.  If results are already known then 

Simulator Interactions:
In simulator "Student is writing a program? not clear" Correct it

**Comment by dratul** [comment]
Responses:
Round 0
--Corrections have been made in about the lab, removed faculty name from the contributor list
Round 1: We are adding reinforce theoretical concept because the concepts and expected results are already known to the user.
